service: firstProject

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: xergioalex

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
